import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Guitar LA</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel='icon' href="favicon.ico"/>
      </Head>
      <h2>Desde el inicio</h2>
      <Link href="/nosotros">A Nosotros</Link>
    </div>
  )
}
